version: '3'
services:
    php-apache:
        build:
          context: .
          dockerfile: PHP.Dockerfile
        ports:
            - "3000:80"
        volumes:
            - ../src:/var/www/html/src
            - ../SQL:/var/www/html/SQL
            - ../vendor:/var/www/html/vendor
            - ../.env:/var/www/html/.env
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - ../.env
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}